### ISSUE TITLE
Implement support for languages other than German and English in com.jcabi.ssl.maven.plugin.Keytool#createLocaleDependentYes

### ISSUE THREAD

**Issue by dpisarenko** [jcabi/jcabi-ssl-maven-plugin#11]
See `com.jcabi.ssl.maven.plugin.Keytool#createLocaleDependentYes`:
```
    /**
     * Creates a text, which represents "yes" in either English or German
     * language, depending on the locale.
     * @return Return "Ja", if the locale is German, "Yes" otherwise.
     */
    private String createLocaleDependentYes() {
        final String language = Locale.getDefault().getLanguage();
        final String yes;
        /**
         * @todo #11:30m/DEV Currently, the implementation below recognizes only
         *  German and English locales. It should be extended so that other
         *  locales (e. g. Spanish) is supported as well. If a particular
         *  locale is not supported, the user should get a hint about that.
         */
        if ("de".equals(language)) {
            yes = "Ja";
        } else {
            yes = "Yes";
        }
        return yes;
    }
```

**Comment by dmarkov** [comment]
the last puzzle `11-721ca2c9`/#16 originated from here solved

**Comment by dmarkov** [comment]
@suseika it's your task now

**Comment by Suseika** [comment]
@dpisarenko I fixed this in #36, please see.

**Comment by dmarkov** [comment]
@rultor @dpisarenko please take a look, rultor closed it automatically

**Comment by Suseika** [comment]
@dmarkov I need more time here, the author of the issues isn't responding.

**Comment by Suseika** [comment]
@dpisarenko Please see this issue, it is fixed in #36.

**Comment by Suseika** [comment]
@dmarkov I'm done here, please pay.

**Comment by dmarkov** [comment]
> @dmarkov I need more time here, the author of the issue isn't responding.

@suseika sure, thanks for telling me, take your time

**Comment by Suseika** [comment]
@dmarkov I don't need the time any more, author just closed the task and I mentioned what PR it was closed with. *Please pay.*

**Comment by dmarkov** [comment]
@suseika thank you, added **30 mins** to your acc, payment num is `AP-0T0752365L4683907`, 171 hours and 6 mins spent in total to complete

+30 added to your rating, at the moment it is: [+353](http://www.netbout.com/b/35381?open=rating)
