### ISSUE TITLE
How to get to know the latest release version?

### ISSUE THREAD

**Issue by dpisarenko** [jcabi/jcabi-ssl-maven-plugin#12]
Please add information on how I can get to know the latest release version of jcabi-ssl-maven-plugin.

For example, the bugfix for issue https://github.com/jcabi/jcabi-ssl-maven-plugin/issues/4 was merged. Now I want to know what version I have to write in `pom.xml` of as s3auth proect, which uses jcabi-ssl-maven-plugin in order for that bugfix to be present in s3auth build.

One solution: Provide a short description in README.md on where to get the latest release version.

**Comment by yegor256** [comment]
Here it is: https://github.com/jcabi/jcabi-ssl-maven-plugin/releases (all Github projects have this list in the same place, no need to explain it additionally in README).

**Comment by yegor256** [comment]
@dpisarenko every time you want a new version to be released, ask me right in the ticket. I will release.
