### ISSUE TITLE
Other project needs updated version of jcabi-ssl-maven-plugin

### ISSUE THREAD

**Issue by wentwog** [jcabi/jcabi-ssl-maven-plugin#15]
yegor256/s3auth#191 needs updates intoduced in jcabi-ssl-maven-plugin by #8.
1) We do this through snapshot or release ?
2) How to issue a snapshot or a release ?

**Comment by yegor256** [comment]
0.10 will be released in #8, in a few minutes.

**Comment by yegor256** [comment]
@wentwog every time you need a new release, ask for it in the ticket that introduced a change
