### ISSUE TITLE
Keytool.java:172-175: Currently, the implementation below recognizes...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-ssl-maven-plugin#16]
Puzzle `11-721ca2c9` in `src/main/java/com/jcabi/ssl/maven/plugin/Keytool.java:172-175` has to be resolved: Currently, the implementation below recognizes only German and English locales. It should be extended so that other locales (e. g. Spanish) is supported as well. If a particular locale is not supported, the user should get a hint about that.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@palyuga this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions. Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by palyuga** [comment]
@dmarkov pull request is merged, so we can close this issue

**Comment by dmarkov** [comment]
Closed, done, thanks all

**Comment by dmarkov** [comment]
@palyuga Thanks so much! Your account was topped up for **30 mins** (transaction ID is `50302645`); +30 to your rating, your total score is +135
