### ISSUE TITLE
s3auth build takes a lot of time (seems to hang) #3 - it is not bug

### ISSUE THREAD

**Issue by AlexDag** [jcabi/jcabi-ssl-maven-plugin#20]
I've tried  three(3)times as "mvn clean install -Pqulice".
The process duration had  from 57sec to 1 min.
I see that the person of bug report used Windows OS. 
And procBuilder from Keytool.java run as "%s/bin/keytool" as linux OS process.

thanks

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 57.547 s
[INFO] Finished at: 2015-01-14T20:32:22-03:00
[INFO] Final Memory: 113M/616M
[INFO] ------------------------------------------------------------------------
alex@ubuntu:~/workspace/jcabi-ssl-maven-plugin$

**Comment by yegor256** [comment]
@AlexDag how can I reproduce this issue? I didn't get exactly what is happening and where

**Comment by AlexDag** [comment]
@yegor256  it's from https://github.com/jcabi/jcabi-ssl-maven-plugin/issues/3

**Comment by yegor256** [comment]
@AlexDag so it's a duplicate than
