### ISSUE TITLE
#3 s3auth build takes a lot of time (seems to hang) #3 - it is not bug #20

### ISSUE THREAD

**Issue by AlexDag** [jcabi/jcabi-ssl-maven-plugin#21]
I've tried three(3)times as "mvn clean install -Pqulice".
The process duration had from 57sec to 1 min.
I see that the person of bug report used Windows OS. 
And procBuilder from Keytool.java run as "%s/bin/keytool" as linux OS process.

thanks

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 57.547 s
[INFO] Finished at: 2015-01-14T20:32:22-03:00
[INFO] Final Memory: 113M/616M
[INFO] ------------------------------------------------------------------------
alex@ubuntu:~/workspace/jcabi-ssl-maven-plugin$

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue

**Comment by yegor256** [comment]
@AlexDag doesn't look like a bug for me, 57s is a reasonable time for a build
