### ISSUE TITLE
Cease to use Jfrog Anno Mojo maven plugin and use normal maven xdoclet annotations

### ISSUE THREAD

**Issue by wentwog** [jcabi/jcabi-ssl-maven-plugin#25]
jcabi-ssl-maven-plugin can't be built with Java 8, because we use Jfrog Anno Mojo maven plugin, and it's not ready for Java8 (for details see #13).
It is [decided](https://github.com/jcabi/jcabi-ssl-maven-plugin/issues/13#issuecomment-71197569) to get rid of Jfrog Anno Mojo maven plugin and use normal maven xdoclet annotations.

(Jfrog Anno Mojo allows to use Java5-style annotations instead of writing them in javadoc comments.
We need to switch back to this comments option.)

You can find the plugin's occurrences in pom.xml by searching for `jfrog`.

**Comment by dmarkov** [comment]
we'll find someone to do this task, soon

**Comment by dmarkov** [comment]
@wentwog thanks for tis bug, I topped your account for 15 mins, transaction `50663952`

**Comment by dmarkov** [comment]
@suseika it's yours, please help

**Comment by dmarkov** [comment]
@rultor rultor closed it by mistake, @wentwog please take a look

**Comment by wentwog** [comment]
@Suseika , @dmarkov , looks good, just one comment it the PR, @Suseika, please have a look

**Comment by Suseika** [comment]
@wentwog Thanks, #37 fixes the wrong parameters mistake.

**Comment by Suseika** [comment]
@dmarkov I'm done here, issue is closed with #34

**Comment by dmarkov** [comment]
@wentwog once `25-04bb79eb`/#38 puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by dmarkov** [comment]
@suseika thanks, I just added **30 mins** to your account, payment `AP-2U644454M27957102`, 119 hours and 9 mins spent; +30 added to your rating, current score is: [+233](http://www.netbout.com/b/35381?open=rating)

**Comment by dmarkov** [comment]
@wentwog the last puzzle `25-04bb79eb`/#38 solved
