### ISSUE TITLE
keygen fails on JDK8

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-ssl-maven-plugin#32]
```
[INFO] --- jcabi-ssl-maven-plugin:0.11:keygen (default) @ s3auth ---
[ERROR] JSR-303 validator failed to initialize: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath. (see http://aspects.jcabi.com/jsr-303.html)
[INFO] Existing cacerts '/opt/jdk1.8.0_40/jre/lib/security/cacerts' copied to '/tmp/s3auth/target/cacerts.jks' (30 bytes)
[INFO] jcabi-aspects 0.20.1/f0aff93 started new daemon thread jcabi-loggable for watching of @Loggable annotated methods
[ERROR] #genkey(): thrown java.util.MissingResourceException(Can't find resource for bundle sun.security.util.Resources, key yes) out of java.util.ResourceBundle#getObject[450] in 221ms
[ERROR] #activate(/tmp/s3auth/target/keystore.jks): thrown java.util.MissingResourceException(Can't find resource for bundle sun.security.util.Resources, key yes) out of java.util.ResourceBundle#getObject[450] in 240ms
```

originally reported in https://github.com/yegor256/s3auth/issues/301

**Comment by dmarkov** [comment]
@yegor256 I just added bug tag here

**Comment by dmarkov** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-e70cc75d`

**Comment by dmarkov** [comment]
@suseika this task is yours, go ahead

**Comment by Suseika** [comment]
@yegor256 This is going to be fixed with #36. I didn't mean to fix multiple issues in a single PR, these issues just happen to have the same cause. 

This is the second time I have to fix multiple dependent issues in a single PR, and I was told that is not fine, what should I do in such situations?

**Comment by yegor256** [comment]
@Suseika you should try to avoid that, but sometimes it's inevitable

**Comment by Suseika** [comment]
@yegor256 Fixed with #36

**Comment by yegor256** [comment]
@Suseika thanks!

**Comment by Suseika** [comment]
@dmarkov I'm done here.

**Comment by Suseika** [comment]
@dmarkov This task is closed, but I still haven't received any payment for it. Please pay.

**Comment by dmarkov** [comment]
@suseika **30 mins** added to your account (payment number `AP-20J10789G40751114`), many thanks for your contribution! 144 hours and 57 mins spent here.

+30 added to your rating, current score is: [+293](http://www.netbout.com/b/35381?open=rating)
