### ISSUE TITLE
Keytool.java:173-173: In JDK 1.8, there is...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-ssl-maven-plugin#38]
Puzzle `25-04bb79eb` in `src/main/java/com/jcabi/ssl/maven/plugin/Keytool.java:173-173` has to be resolved: In JDK 1.8, there is no "yes" word in... The puzzle was created by Suseika on 26-Jun-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by Suseika** [comment]
@dmarkov This puzzle was created by a mistake. After I added the todo in a PR, the next issue involved getting rid of the code that caused the behavior described in this todo. So this puzzle is fixed with #36.

**Comment by dmarkov** [comment]
@yegor256 We are done here, thanks all
