### ISSUE TITLE
jcabi-ssl-maven-plugin build fails with 3 test errors

### ISSUE THREAD

**Issue by dpisarenko** [jcabi/jcabi-ssl-maven-plugin#4]
When I run `mvn clean install -Pqulice` the build of `jcabi-ssl-maven-plugin` fails due to errors in tests:

```
Tests in error:
  KeytoolTest.generatesAndActivatesKeystore:62 ╗ IllegalArgument Non-zero exit c
...
  KeystoreTest.generatesAndActivatesKeystore:64 ╗ IllegalArgument Non-zero exit
...
  CacertsTest.importsCertificatesFromKeystore:64 ╗ IllegalArgument Non-zero exit
...

Tests run: 4, Failures: 0, Errors: 3, Skipped: 0
```

Please make sure that it is possible to build `jcabi-ssl-maven-plugin` using `mvn clean install -Pqulice`.

**Comment by dmarkov** [comment]
@dpisarenko thanks for reporting! I topped your account for 15 mins, transaction 49702157

**Comment by pandreev** [comment]
@dmarkov please assign to someone else

**Comment by dmarkov** [comment]
> @dmarkov please assign to someone else

@pandreev no problem, I'll try to find somebody else

**Comment by dmarkov** [comment]
@maurezen please proceed, it's yours

**Comment by maurezen** [comment]
@dmarkov @yegor256 please assign another developer to this task.

**Comment by yegor256** [comment]
@dmarkov give this to someone else pls

**Comment by dmarkov** [comment]
> @dmarkov give this to someone else pls

@yegor256 all right, we'll find someone else for this task

**Comment by dmarkov** [comment]
@apocarteres the issue is yours, please help

**Comment by apocarteres** [comment]
@dpisarenko is anything else needed to be done under this issue? It seems that everything woks correct now for Windows / Linux with German/Russian locales. Could you confirm?

**Comment by dpisarenko** [comment]
@apocarteres The tests above don't fail any more, but we have another problem - see https://github.com/jcabi/jcabi-ssl-maven-plugin/issues/27 .

**Comment by dmarkov** [comment]
@apocarteres paid, thanks, added **30 mins** to your account, payment `50954672`; +30 to your rating, your total score is [+120](http://www.netbout.com/b/35111?open=rating)
